name: Frontend Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            echo "STEP 1: Go to project directory"
            cd /home/ec2-user/Superapp_Frontend || exit 1

            echo "STEP 2: Pull latest code"
            git pull origin main || exit 1

            echo "STEP 3: Install dependencies"
            npm install || exit 1

            echo "STEP 4: Build frontend"
            npm run build || exit 1

            echo "STEP 5: Deploy build to nginx"
            sudo rm -rf /usr/share/nginx/html/* || exit 1
            sudo cp -r build/* /usr/share/nginx/html/ || exit 1

            echo "STEP 6: Reload nginx"
            sudo systemctl reload nginx || exit 1

            echo "âœ… DEPLOYMENT SUCCESS"
